"""
Payment MCP Server for AI Employee
Implements Model Context Protocol to handle payment processing with appropriate safety measures
"""

import asyncio
import json
import logging
import uuid
from datetime import datetime
from typing import Dict, Any, List
from pathlib import Path
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class PaymentMCPServer:
    """
    MCP Server for payment processing tasks with human-in-the-loop safety
    """

    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.pending_approvals = self.vault_path / 'Pending_Approval'
        self.approved = self.vault_path / 'Approved'
        self.rejected = self.vault_path / 'Rejected'
        self.logs = self.vault_path / 'Logs'

        # Create directories if they don't exist
        self.pending_approvals.mkdir(exist_ok=True)
        self.approved.mkdir(exist_ok=True)
        self.rejected.mkdir(exist_ok=True)
        self.logs.mkdir(exist_ok=True)

        # Setup logging
        self.logger = logging.getLogger('PaymentMCP')
        handler = logging.FileHandler(self.logs / 'payment_mcp.log')
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        handler.setFormatter(formatter)
        self.logger.addHandler(handler)
        self.logger.setLevel(logging.INFO)

        # Payment thresholds
        self.autopay_threshold = 50.0  # Amount under which payments can auto-process
        self.new_payee_threshold = 100.0  # Amount that requires extra approval for new payees

    def create_payment_approval_request(self, payment_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create an approval request file for payment processing
        """
        try:
            # Generate unique ID for the payment
            payment_id = f"PAYMENT_{uuid.uuid4().hex[:8].upper()}_{int(datetime.now().timestamp())}"
            filename = f"{payment_id}.md"

            # Create approval request content
            approval_content = f"""---
type: approval_request
action: payment
payment_id: {payment_id}
amount: {payment_data.get('amount', 0.0)}
recipient: {payment_data.get('recipient', 'Unknown')}
reason: {payment_data.get('reason', 'No reason provided')}
created: {datetime.now().isoformat()}
expires: {datetime.now().replace(day=datetime.now().day+1).isoformat()}  # Expires in 24 hours
status: pending
is_new_payee: {payment_data.get('is_new_payee', False)}
---

# Payment Approval Request

## Payment Details
- **Amount**: ${payment_data.get('amount', 0.0)}
- **To**: {payment_data.get('recipient', 'Unknown')} ({payment_data.get('recipient_account', 'No account info')})
- **Reason**: {payment_data.get('reason', 'No reason provided')}
- **Payment Method**: {payment_data.get('method', 'Unknown')}

## Transaction Information
- **Description**: {payment_data.get('description', 'No description')}
- **Category**: {payment_data.get('category', 'General')}
- **Reference**: {payment_data.get('reference', 'No reference')}

## To Approve
Move this file to /Approved folder to authorize the payment.

## To Reject
Move this file to /Rejected folder with reason.

---
*Generated by AI Employee Payment MCP*
"""

            # Write approval request to pending folder
            approval_file = self.pending_approvals / filename
            approval_file.write_text(approval_content)

            result = {
                "success": True,
                "payment_id": payment_id,
                "status": "approval_created",
                "approval_file": str(approval_file),
                "message": f"Payment request created. Awaiting approval for ${payment_data.get('amount', 0.0)} to {payment_data.get('recipient', 'Unknown')}"
            }

            self.logger.info(f"Created payment approval request {payment_id}")
            return result
        except Exception as e:
            self.logger.error(f"Failed to create payment approval: {e}")
            return {"success": False, "error": str(e)}

    def process_approved_payment(self, approval_file_path: str) -> Dict[str, Any]:
        """
        Actually process an approved payment
        """
        try:
            file_path = Path(approval_file_path)

            # Read the approval file
            content = file_path.read_text()

            # Extract payment information from the file
            lines = content.split('\n')
            payment_info = {}

            for line in lines:
                if ': ' in line and line.startswith('- '):
                    # Parse payment details line like "- **Amount**: $100.00"
                    if '**Amount**' in line:
                        amount_str = line.split('$')[1].split()[0]
                        payment_info['amount'] = float(amount_str)
                    elif '**To**' in line:
                        # Extract recipient name
                        start = line.find('**To**: ') + 8
                        end = line.find(' (', start)
                        if end != -1:
                            payment_info['recipient'] = line[start:end]
                        else:
                            payment_info['recipient'] = line[start:].split('**')[0].strip()

            # In a real implementation, this would connect to actual payment APIs
            # For safety in this example, we'll just log the intent and return
            result = {
                "success": True,
                "status": "payment_processed_sim",
                "message": f"Payment of ${payment_info.get('amount', 'unknown')} to {payment_info.get('recipient', 'unknown')} would be processed in production",
                "payment_method": "simulated"
            }

            # Log the payment attempt
            log_entry = {
                "timestamp": datetime.now().isoformat(),
                "action": "payment_processed",
                "amount": payment_info.get('amount'),
                "recipient": payment_info.get('recipient'),
                "file_path": str(file_path)
            }

            log_file = self.logs / f"payment_log_{datetime.now().strftime('%Y-%m-%d')}.json"
            with open(log_file, 'a') as f:
                f.write(json.dumps(log_entry) + '\n')

            self.logger.info(f"Processed approved payment: ${payment_info.get('amount', 'unknown')} to {payment_info.get('recipient', 'unknown')}")
            return result
        except Exception as e:
            self.logger.error(f"Failed to process approved payment: {e}")
            return {"success": False, "error": str(e)}

    def verify_payee(self, recipient: str) -> Dict[str, Any]:
        """
        Verify if a payee is known/previously used
        """
        try:
            # In a real implementation, this would check against a database of known payees
            # For this example, we'll just simulate by checking if the recipient name is in a basic list
            known_payees = [
                "Client A", "Client B", "Client C",  # Example clients
                "Amazon", "Microsoft", "Adobe",      # Example vendors
                "Office Rent", "Internet Service", "Electricity"  # Example services
            ]

            is_known = recipient in known_payees

            result = {
                "success": True,
                "is_known": is_known,
                "recipient": recipient,
                "status": "verified"
            }

            self.logger.info(f"Payee verification: {recipient} is {'known' if is_known else 'new'}")
            return result
        except Exception as e:
            self.logger.error(f"Failed to verify payee: {e}")
            return {"success": False, "error": str(e)}

    def handle_payment_request(self, payment_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Main method to handle a payment request
        """
        try:
            recipient = payment_data.get('recipient', '')

            # Verify if payee is known
            verification_result = self.verify_payee(recipient)

            # Check if payment amount requires approval
            amount = float(payment_data.get('amount', 0))

            # Determine if approval is needed
            needs_approval = True  # Default to requiring approval for safety

            if amount < self.autopay_threshold and verification_result.get('is_known', False):
                # Small payment to known payee - could auto-process
                needs_approval = True  # Still requiring approval for gold tier security
            elif amount < self.new_payee_threshold and not verification_result.get('is_known', False):
                # Payment to new payee under threshold
                needs_approval = True
            elif amount >= self.new_payee_threshold:
                # Large payment - definitely needs approval
                needs_approval = True

            # Add the verification result to the payment data
            payment_data['is_new_payee'] = not verification_result.get('is_known', False)

            if needs_approval:
                # Create approval request
                return self.create_payment_approval_request(payment_data)
            else:
                # Process directly (though this is rare for Gold tier)
                result = {
                    "success": True,
                    "status": "direct_processing",
                    "message": f"Payment of ${amount} would be processed directly (not implemented for safety)"
                }
                self.logger.info(f"Direct payment processing for ${amount}")
                return result

        except Exception as e:
            self.logger.error(f"Failed to handle payment request: {e}")
            return {"success": False, "error": str(e)}

    def handle_refund_request(self, refund_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Handle a refund request
        """
        try:
            # Create approval request for refund
            refund_data['reason'] = refund_data.get('reason', 'Refund request')
            refund_data['recipient'] = refund_data.get('original_recipient', 'Original Recipient')

            return self.create_payment_approval_request({
                'amount': refund_data.get('amount', 0),
                'recipient': refund_data.get('original_recipient', 'Original Recipient'),
                'reason': f"REFUND: {refund_data.get('reason', 'Unknown')}",
                'description': f"Refund for transaction {refund_data.get('original_transaction_id', 'Unknown')}",
                'category': 'Refund',
                'reference': refund_data.get('original_transaction_id', 'Unknown'),
                'method': refund_data.get('method', 'original_payment_method'),
                'is_new_payee': False
            })
        except Exception as e:
            self.logger.error(f"Failed to handle refund request: {e}")
            return {"success": False, "error": str(e)}

    def get_payment_status(self, payment_id: str) -> Dict[str, Any]:
        """
        Get the status of a payment
        """
        try:
            # Check all possible locations for the payment file
            status = "unknown"
            file_path = None

            for folder in [self.pending_approvals, self.approved, self.rejected]:
                for file in folder.glob(f"*{payment_id}*.md"):
                    if folder == self.pending_approvals:
                        status = "pending_approval"
                    elif folder == self.approved:
                        status = "approved"
                    elif folder == self.rejected:
                        status = "rejected"
                    file_path = str(file)
                    break
                if status != "unknown":
                    break

            result = {
                "success": True,
                "payment_id": payment_id,
                "status": status,
                "file_path": file_path
            }

            self.logger.info(f"Payment status check for {payment_id}: {status}")
            return result
        except Exception as e:
            self.logger.error(f"Failed to get payment status: {e}")
            return {"success": False, "error": str(e)}

    # MCP Protocol Methods
    def handle_request(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Handle incoming MCP requests"""
        method = request.get('method', '')
        params = request.get('params', {})

        self.logger.info(f"Handling payment MCP request: {method}")

        if method == 'payment/process':
            return self.handle_payment_request(params)
        elif method == 'payment/refund':
            return self.handle_refund_request(params)
        elif method == 'payment/status':
            return self.get_payment_status(params.get('payment_id', ''))
        elif method == 'payment/verifyPayee':
            return self.verify_payee(params.get('recipient', ''))
        else:
            self.logger.warning(f"Unknown payment method: {method}")
            return {"success": False, "error": f"Unknown method: {method}"}


# Example usage and testing
if __name__ == "__main__":
    # Example of how to use the payment server
    vault_path = Path(__file__).parent  # Use current directory as vault for testing
    server = PaymentMCPServer(vault_path)

    # Example payment request
    payment_request = {
        'amount': 250.00,
        'recipient': 'Client A',
        'reason': 'Payment for completed project work',
        'description': 'Final payment for Project Alpha - Website redesign',
        'category': 'Client Payment',
        'reference': 'INV-2026-001',
        'method': 'ACH Transfer'
    }

    result = server.handle_payment_request(payment_request)
    print(json.dumps(result, indent=2))